# Generated by Django 5.2.7 on 2025-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_del',
            field=models.BooleanField(default=0),
        ),
    ]
