# Generated by Django 5.2.7 on 2025-11-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_tasklist_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='host',
        ),
    ]
