# Generated by Django 5.2.7 on 2025-11-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_tasklist_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='completed',
            field=models.BooleanField(default=0),
        ),
    ]
